version: '2'

services:

  collector:
    build: ./collector
    image: 078791716679.dkr.ecr.eu-west-1.amazonaws.com/rpc-demo/collector
    depends_on: 
      - archiver
    environment: 
      - SEARCH_TERMS=Amazon
      - ARCHIVE_ENDPOINT=http://archiver:8080 
      - AWS_REGION=eu-west-1
    volumes:
      - $HOME/.aws:/root/.aws

  archiver: 
    build: ./archiver
    image: 078791716679.dkr.ecr.eu-west-1.amazonaws.com/rpc-demo/archiver
    environment: 
      - KINESIS_STREAM_NAME=Development-tweets
      - AWS_REGION=eu-west-1
    ports: 
      - "8080:8080"
    volumes:
      - $HOME/.aws:/root/.aws
   
